/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosMessages
{
    public class PoseStampedSimple : Message
    {
        public const string RosMessageName = "teachin/PoseStampedSimple";

        //  PoseStampedSimple.msg
        public Point position { get; set; }
        public Quaternion orientation { get; set; }

        public PoseStampedSimple()
        {
            this.position = new Point();
            this.orientation = new Quaternion();
        }

        public PoseStampedSimple(Point position, Quaternion orientation)
        {
            this.position = position;
            this.orientation = orientation;
        }
    }
}
#endif
