/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.TeachinUnity;

namespace RosSharp.RosBridgeClient.MessageTypes.TeachinUnity
{
    public class PoseStampedSimpleArray : Message
    {
        public const string RosMessageName = "teachin_unity/PoseStampedSimpleArray";

        //  PoseStampedSimpleArray.msg
        public PoseStampedSimple[] poses { get; set; }

        public PoseStampedSimpleArray()
        {
            this.poses = new PoseStampedSimple[0];
        }

        public PoseStampedSimpleArray(PoseStampedSimple[] poses)
        {
            this.poses = poses;
        }
    }
}
#endif
